#version 450
#extension GL_GOOGLE_include_directive : enable

#include "kernels.comp.kern"

layout(local_size_x = 64) in;

layout(set = 0, binding = 0) buffer Data {
    double values[];
};

layout(set = 0, binding = 1) buffer outputData {
    double outvalues[];
};

// Binding 1: uniform buffer (constants)
layout(set = 0, binding = 2) uniform Params {
    float val;
} params;


void main() {
    uint index = gl_GlobalInvocationID.x;
    outvalues[index] = 2.0 * values[index];
}